#ifdef DO_LET_IS_DO
#ifndef DO_LET_IS_SHORT_DO
#define DO_LET_IS_SHORT_DO

#define DO DO_LET_IS_DO
#define DO_GLOBAL DO_LET_IS_DO_GLOBAL
#define LET DO_LET_IS_LET
#define IS DO_LET_IS_IS
#define IF DO_LET_IS_IF
#define IF_CONSTEXPR DO_LET_IS_IF_CONSTEXPR
#define IF_CONSTEVAL DO_LET_IS_IF_CONSTEVAL
#define WHILE DO_LET_IS_WHILE
#define CONTINUE DO_LET_IS_CONTINUE
#define BREAK DO_LET_IS_BREAK

#endif
#endif

#ifdef DO_LET_IS_GENERATOR
#ifndef DO_LET_IS_SHORT_GENERATOR
#define DO_LET_IS_SHORT_GENERATOR

#define GENERATOR DO_LET_IS_GENERATOR
#define YIELD DO_LET_IS_YIELD

#endif
#endif

#ifdef DO_LET_IS_GENERATOR_LOOPHOLES
#ifndef DO_LET_IS_SHORT_GENERATOR_LOOPHOLES
#define DO_LET_IS_SHORT_GENERATOR_LOOPHOLES

#define GENERATOR_LOOPHOLES DO_LET_IS_GENERATOR_LOOPHOLES

#endif
#endif
